# Generated by Django 6.0.4 on 2026-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0002_order_payment_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='milk',
            field=models.CharField(blank=True, default='Whole', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default='16 oz', max_length=10),
        ),
    ]
