# Generated by Django 6.0.4 on 2026-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0003_add_size_milk_to_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
    ]
