# Generated by Django 6.0.4 on 2026-06-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0004_remove_orderitem_milk_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (Unsplash, CDN, etc.)', null=True),
        ),
    ]
